# Required
Disease/Phenotype terms: epilep, seizure

# Optional
Additional associated terms: brain, nerve, nervous, neuronal, cerebellum, cerebral, hippocampus, hypothalamus
Diseases/Phenotypes to exclude: 
